import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
var HeroSection = function () {
    var navigate = useNavigate();
    var handleSignUp = function () {
        navigate('/signup');
    };
    return (_jsxs("div", { id: "hero", className: "flex flex-col lg:flex-row items-start justify-between gap-4 lg:gap-14 p-4 lg:p-10 lg:px-16 mt-20 lg:mt-0 xl:mt-14 w-full lg:bg-gradient-to-br lg:from-[#F9D2FF] lg:to-[#8DA6FF] bg-[#F9D2FF]", children: [_jsxs("div", { className: "w-full lg:w-1/2 text-left flex flex-col gap-8 xl:gap-24", children: [_jsxs("div", { className: "flex flex-col gap-4 order-1 lg:order-1", children: [_jsxs("h1", { className: "text-5xl leading-[50px] lg:text-6xl lg:leading-[70px] xl:text-7xl xl:leading-[100px] font-medium text-[#30175A]", children: ["Elevate Your ", _jsx("br", {}), " Social Media ", _jsx("br", {}), " Presence with ", _jsx("br", {}), " Matchpoint"] }), _jsxs("p", { className: "text-2xl hidden xl:block leading-8 lg:text-3xl lg:leading-9 text-indigo-900 font-medium md:mb-8", children: ["Unleash the power of AI to create ", _jsx("br", {}), " stunning visuals and captivating copy."] })] }), _jsx("div", { className: "flex flex-col gap-4 order-2 lg:order-3", children: _jsx("button", { onClick: handleSignUp, className: "bg-pink-500 hover:bg-pink-600 text-white font-medium text-base rounded-lg w-fit h-auto px-5 py-3 md:px-5 md:py-3", children: "Start Creating Content For Free" }) }), _jsx("div", { className: "flex xl:hidden flex-col gap-4 order-3 lg:order-2", children: _jsx("p", { className: "text-2xl leading-8 lg:text-3xl lg:leading-9 text-indigo-900 font-medium md:mb-8", children: "Unleash the power of AI to create stunning visuals and captivating copy." }) })] }), _jsx("div", { className: "lg:w-1/2 flex justify-center lg:mt-0", children: _jsx("div", { className: "relative rounded-lg overflow-hidden", children: _jsx("img", { src: "poster.png", alt: "Main visual", className: "w-full h-auto object-cover" }) }) })] }));
};
export default HeroSection;
//# sourceMappingURL=HeroSection.js.map